### ISSUE TITLE
Investigate test-inspector-break-when-eval failure

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/node-chakracore#294] opened 2017-06-12 20:32 UTC
https://github.com/nodejs/node-chakracore/pull/293 marked test-inspector-break-when-eval as flaky. Investigate and re-enable it.

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by kfarnung** [comment] 2017-06-12 20:34
Duplicate of #292.

**Closed as completed by kfarnung** 2017-06-12 20:34 UTC
