### ISSUE TITLE
Nightly Arm Binaries

### ISSUE THREAD

**Issue by Cellule** [nodejs/node-chakracore#256] opened 2017-05-22 22:43 UTC
There used to be Arm binaries of Node-ChakraCore
The last one produced was on May 4th:
https://nodejs.org/download/chakracore-nightly/v8.0.0-nightly201705047f33b4cbf3/

In the latest build after that, there were no arm binaries available.

Also, in the [index.json](https://nodejs.org/download/chakracore-nightly/index.json) file, there were no entries for arm in the `files` field which prevent `nvs` from finding arm binaries.
```json
{
  "version": "v8.0.0-nightly201705047f33b4cbf3",
  "date": "2017-05-04",
  "files": ["headers", "linux-x64", "osx-x64-tar", "win-x64-exe", "win-x86-exe"],
  "v8": "",
  "uv": "",
  "zlib": null,
  "openssl": null,
  "modules": null,
  "lts": false
}
```

Is it expected to not produce arm binaries anymore ?
Are they not supported ?

**Comment by kfarnung** [comment] 2017-05-22 22:45
@kunalspathak @digitalinfinity were looking into this, I'm not sure of the status.

**Comment by kunalspathak** [comment] 2017-05-22 22:46
Duplicate of https://github.com/nodejs/node-chakracore/issues/240

**Closed as completed by kunalspathak** 2017-05-22 22:46 UTC

**Comment by Cellule** [comment] 2017-05-22 22:50
Oh Thanks,
I had a todo to open an issue, I didn't know you opened one since.
