### ISSUE TITLE
SyntaxError occures during benchmark run

### ISSUE THREAD

**Issue by abodalevsky** [nodejs/node-chakracore#134] opened 2016-10-17 12:54 UTC
- **Version**:v7.0.0-pre
- **Platform**:Windows x64 v: 10.0.10240
- **Subsystem**:

When I tried to execute benchmark test _benchmark\buffers\buffer-compare-instance-method.js_ I got the following error:

```
SyntaxError: Syntax error                                                                                                                                                              
   at main (E:\Projects\Git\node-chakracore\benchmark\buffers\buffer-compare-instance-method.js:21:3)                                                                                  
   at Anonymous function (E:\Projects\Git\node-chakracore\benchmark\common.js:24:28)                                                                                                   
   at _combinedTickCallback (internal/process/next_tick.js:67:7)                                                                                                                       
   at _tickCallback (internal/process/next_tick.js:98:9)                                                                                                                               
   at Module.runMain (module.js:596:3)                                                                                                                                                 
   at run (bootstrap_node.js:382:7)                                                                                                                                                    
   at startup (bootstrap_node.js:137:9)                                                                                                                                                
   at Anonymous function (bootstrap_node.js:497:3) 
```

to reproduce, go to _benchmark\buffers_ and run:

``` js
node buffer-compare-instance-method.js
```

The same test runs on node/v8 without issues

**Comment by digitalinfinity** [comment] 2016-10-17 17:46
Thanks @abodalevsky - I can repro this. I think the problem is that node-cc doesn't support some internal v8 methods today- the problem is this line in the benchmark:
  eval('%OptimizeFunctionOnNextCall(b0.compare)');

%OptimizeFunctionOnNextCall appears to be an internal v8 method. node-chakracore doesn't support shimming v8 internal methods today (since they're supposed to be internal to v8).

@kunalspathak @Jianchun - can you guys confirm this is the case?

**Comment by kunalspathak** [comment] 2016-10-17 17:51
That's correct. Most of these functions that are exposed using `--allow_natives_syntax` are not supported in chakrashim.

**Comment by matthargett** [comment] 2016-10-17 18:57
Can those benchmarks be disabled in node-chakracore somehow?

**Comment by digitalinfinity** [comment] 2016-10-17 19:09
@joaocgreis can you help? Is it possible to disable these benchmarks in node-chakracore? Would the changes you made to CI recently help on this front?

**Comment by joaocgreis** [comment] 2016-10-18 16:23
@digitalinfinity The tests and the benchmarks use different runners, the benchmarks' runner is less complex and it's not possible to disable benchmarks. What we could do is add a `if (process.jsEngine === 'chakracore')` to the unsupported benchmarks to skip them.

For a rough comparison, those lines can probably be skipped, but it wouldn't be a truthful comparison then.

cc @bzoz

**Comment by matthargett** [comment] 2016-10-29 02:09
As a user, I'd rather have something that just runs out of the box and I can compare the benchmarks that do actually run between v8 and chakracore, or between chakracore releases.

**Comment by bzoz** [comment] 2017-03-06 15:41
Fixed by https://github.com/nodejs/node/pull/9615

**Closed as completed by bzoz** 2017-03-06 15:41 UTC
